### ISSUE TITLE
Cant find grammar for Nist keyword.

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-model-iso#43]
We have a `keyword` attribute in a `nist.rnc`. But I can't find where is the `keyword` described.
```
BibData =
    attribute type { BibItemType }?,
    btitle+, formattedref?, bsource*, nistdocidentifier*, docnumber?, bdate*, contributor*,
    edition?, version?,
    biblionote*, language*, script*, abstract*, status?, copyright,
    docrelation*, nistseries?, nistsubseries?, editorialgroup, ics*, security?, keyword+,
    commentperiod
}
```

**Comment by opoudjis** [comment]
The inheritance chain is biblio.rnc > isodoc.rnc > isostandard.rnc > nist.rnc. I agree that's not great, and there is an open ticket, https://github.com/metanorma/relaton/issues/39,  to rationalise bibitem so it is entirely consistent across all gems, by being restricted to biblio.rnc (or at least minimising customisations to it).

keyword is defined in isodoc.rnc, as 

`keyword = element keyword { PureTextElement* }`
`PureTextElement =  text | em | strong | sub | sup | tt | keyword | strike | smallcap | br`

As it turns out, keyword is a formatting element, like `strong` and `em`, so it was going to end up shared with biblio as formatting anyway. One could argue that's an overloading; I'm not convinced it is.

The definition involves mutual recursion, but given formatting like `<strong><em>`, that definition is inevitable.
